title: Zetkin Foundation
email: info@zetkin.org
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zetkin.org" # the base hostname & protocol for your site
github_username:  zetkin

# Build settings
exclude: [Dockerfile]
markdown: kramdown
gems:
    - jekyll-sitemap

defaults:
    -   scope:
            path: ""
        values:
            layout: "default"
