version: "2.2"
volumes:
    dbdata:
services:
    www:
        build: ./backend
        ports:
            - 80:8000
        links:
            - db:db
        volumes:
            - ./backend:/var/app
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: django
        volumes:
            - dbdata:/var/lib/postgresql/data
